name = "external-auth-rule-eval"
account_id = "36ddb61117ace3ebf47bbc1e91502a71"
workers_dev = false
compatibility_date = "2022-06-10"
main = "index.js"

kv_namespaces = [
    # namespace: 
  { binding = "KV", id = "e670f5f0822349d697f904745a24967a", preview_id = "e670f5f0822349d697f904745a24967a" },
]

[vars]
TEAM_DOMAIN="jdores.cloudflareaccess.com"
DEBUG=false

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
